Repository GENIE-MC/Generator, pull requests merged in 2021-06, with the labels that each got.

#159 Bosted-Christy fit
  config/BostedChristyEMPXSec.xml
  config/master_config.xml
  src/Physics/Resonance/XSection/BostedChristyEMPXSec.cxx
  src/Physics/Resonance/XSection/BostedChristyEMPXSec.h
  src/Physics/Resonance/XSection/LinkDef.h
Labels: Cross sections

#165 Susa tunes
  config/G21_11a/CommonParam.xml
  config/G21_11a/EventGenerator.xml
  config/G21_11a/MECInteractionListGenerator.xml
  config/G21_11a/ModelConfiguration.xml
  config/G21_11a/TuneGeneratorList.xml
  config/G21_11b/CommonParam.xml
  config/G21_11b/EventGenerator.xml
  config/G21_11b/MECInteractionListGenerator.xml
  config/G21_11b/ModelConfiguration.xml
  config/G21_11b/TuneGeneratorList.xml
  config/GEM21_11a/CommonParam.xml
  config/GEM21_11a/EventGenerator.xml
  config/GEM21_11a/MECInteractionListGenerator.xml
  config/GEM21_11a/ModelConfiguration.xml
  config/GEM21_11a/TuneGeneratorList.xml
  config/GEM21_11b/CommonParam.xml
  config/GEM21_11b/EventGenerator.xml
  config/GEM21_11b/MECInteractionListGenerator.xml
  config/GEM21_11b/ModelConfiguration.xml
  config/GEM21_11b/TuneGeneratorList.xml
Labels: Tune

#162 Qvalue shift new
  config/QvalueShifter.xml
  config/master_config.xml
  src/Physics/Common/LinkDef.h
  src/Physics/Common/QvalueShifter.cxx
  src/Physics/Common/QvalueShifter.h
  src/Physics/Multinucleon/XSection/NievesSimoVacasMECPXSec2016.cxx
  src/Physics/Multinucleon/XSection/NievesSimoVacasMECPXSec2016.h
  src/Physics/Multinucleon/XSection/SuSAv2MECPXSec.cxx
  src/Physics/Multinucleon/XSection/SuSAv2MECPXSec.h
  src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.cxx
  src/Physics/QuasiElastic/XSection/SuSAv2QELPXSec.h
Labels: Cross sections, good first issue

#157 Cross section model for linear combinations
  config/G18_10a/ModelConfiguration.xml
  config/NievesQELCCPXSec.xml
  config/XSecLinearCombinations.xml
  config/master_config.xml
  src/Physics/Common/LinkDef.h
  src/Physics/Common/XSecLinearCombinations.cxx
  src/Physics/Common/XSecLinearCombinations.h
Labels: Cross sections, Framework

#169 remove unimplmented declaration
  src/Physics/Multinucleon/EventGen/MECGenerator.h
Labels: bug, good first issue
